import { useState, useEffect, useCallback } from 'react';
import { GoogleMap, useJsApiLoader, Marker, DirectionsRenderer } from '@react-google-maps/api';
import Navbar from '../components/Navbar';
import { trackingAPI } from '../services/api';
import socketService from '../services/socket';

const containerStyle = { width: '100%', height: '100%' };
const center = { lat: 30.3165, lng: 78.0322 }; // Dehradun

const StudentDashboard = () => {
  const { isLoaded } = useJsApiLoader({
    id: 'google-map-script',
    googleMapsApiKey: import.meta.env.VITE_GOOGLE_MAPS_API_KEY
  });

  const [map, setMap] = useState(null);
  const [routes, setRoutes] = useState([]);
  const [selectedRoute, setSelectedRoute] = useState('');
  const [buses, setBuses] = useState([]);
  const [selectedBus, setSelectedBus] = useState(null);
  const [loading, setLoading] = useState(true);
  const [busLocations, setBusLocations] = useState({});
  const [directionsResponse, setDirectionsResponse] = useState(null);

  const onLoad = useCallback(function callback(map) {
    setMap(map);
  }, []);

  const onUnmount = useCallback(function callback(map) {
    setMap(null);
  }, []);

  // Fetch routes and setup sockets
  useEffect(() => {
    fetchRoutes();
    socketService.connect();

    socketService.onReceiveLocation((data) => {
      setBusLocations(prev => ({
        ...prev,
        [data.busId]: {
          lat: data.lat,
          lng: data.lng,
          availableSeats: data.availableSeats,
          timestamp: data.timestamp
        }
      }));
    });

    socketService.onBusStatusChanged((data) => {
      setBuses(prev => prev.map(bus => 
        bus._id === data.busId ? { ...bus, isActive: data.isActive } : bus
      ));
    });

    return () => {
      socketService.off('receiveLocation');
      socketService.off('busStatusChanged');
      socketService.disconnect();
    };
  }, []);

  // Handle Route Selection
  useEffect(() => {
    if (selectedRoute) {
      fetchBusesByRoute(selectedRoute);
      fetchAndDrawRoute(selectedRoute);
    } else {
      setBuses([]);
      setDirectionsResponse(null);
    }
  }, [selectedRoute]);

  const fetchRoutes = async () => {
    try {
      const response = await trackingAPI.getRoutes();
      setRoutes(response.data);
    } catch (error) {
      console.error('Error fetching routes:', error);
    }
    setLoading(false);
  };

  const fetchBusesByRoute = async (routeId) => {
    try {
      const response = await trackingAPI.getBusesByRoute(routeId);
      setBuses(response.data);
    } catch (error) {
      console.error('Error fetching buses:', error);
    }
  };

  const fetchAndDrawRoute = async (routeId) => {
    try {
      const response = await trackingAPI.getRouteDetails(routeId);
      const route = response.data;
      
      if (route.stops && route.stops.length >= 2) {
        const directionsService = new window.google.maps.DirectionsService();
        
        // Use stop names + City to force Google to find real-world roads, 
        // ignoring the fake coordinates generated by the backend
        const origin = `${route.stops[0].name}, Dehradun, India`;
        const destination = `${route.stops[route.stops.length - 1].name}, Dehradun, India`;
        
        const waypoints = route.stops.slice(1, -1).map(stop => ({
          location: `${stop.name}, Dehradun, India`,
          stopover: true
        }));

        const results = await directionsService.route({
          origin: origin,
          destination: destination,
          waypoints: waypoints,
          travelMode: window.google.maps.TravelMode.DRIVING, // Crucial for snapping to roads
        });

        setDirectionsResponse(results);
      }
    } catch (error) {
      console.error('Error calculating directions:', error);
    }
  };

  const getSelectedRouteName = () => {
    const route = routes.find(r => r._id === selectedRoute);
    return route ? route.routeName : '';
  };

  return (
    <div className="min-h-screen bg-gray-100">
      <Navbar />
      
      <div className="flex flex-col lg:flex-row h-[calc(100vh-64px)]">
        {/* Sidebar */}
        <div className="w-full lg:w-96 bg-white shadow-lg overflow-y-auto">
          <div className="p-4 border-b">
            <h1 className="text-xl font-bold text-gray-800 mb-4">Track Buses</h1>
            
            <div className="mb-4">
              <label className="block text-sm font-medium text-gray-700 mb-2">Select Route</label>
              <select
                value={selectedRoute}
                onChange={(e) => {
                  setSelectedRoute(e.target.value);
                  setSelectedBus(null);
                }}
                className="w-full px-4 py-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-primary-500 focus:border-transparent outline-none"
              >
                <option value="">-- Select a Route --</option>
                {routes.map(route => (
                  <option key={route._id} value={route._id}>
                    {route.routeNumber} - {route.routeName}
                  </option>
                ))}
              </select>
            </div>
            {selectedRoute && <p className="text-sm text-gray-500">Route: {getSelectedRouteName()}</p>}
          </div>

          {/* Bus List & Details (Unchanged from your original code) */}
          {selectedRoute && (
            <div className="p-4">
              <h2 className="text-lg font-semibold text-gray-800 mb-3">Buses on this Route ({buses.length})</h2>
              {buses.length === 0 ? (
                <p className="text-gray-500 text-center py-4">No buses on this route</p>
              ) : (
                <div className="space-y-3">
                  {buses.map(bus => (
                    <div key={bus._id} onClick={() => setSelectedBus(bus)} className={`p-4 rounded-lg border-2 cursor-pointer transition-all ${selectedBus?._id === bus._id ? 'border-primary-500 bg-primary-50' : 'border-gray-200 hover:border-gray-300'}`}>
                      <div className="flex items-center justify-between mb-2">
                        <span className="font-semibold text-gray-800">{bus.busNumber}</span>
                        <span className={`px-2 py-1 text-xs rounded-full ${bus.isActive ? 'bg-green-100 text-green-800' : 'bg-gray-100 text-gray-600'}`}>
                          {bus.isActive ? 'Active' : 'Inactive'}
                        </span>
                      </div>
                      <div className="text-sm text-gray-600">
                        <p>Driver: {bus.driverId?.name}</p>
                        <p>Seats: {busLocations[bus._id]?.availableSeats ?? bus.availableSeats}/{bus.totalSeats}</p>
                      </div>
                    </div>
                  ))}
                </div>
              )}
            </div>
          )}
        </div>

        {/* Map Area */}
        <div className="flex-1 relative">
          {!isLoaded ? (
            <div className="absolute inset-0 flex items-center justify-center bg-gray-100">Loading Map...</div>
          ) : (
            <GoogleMap
              mapContainerStyle={containerStyle}
              center={center}
              zoom={12}
              onLoad={onLoad}
              onUnmount={onUnmount}
            >
              {/* Draw Route */}
              {directionsResponse && (
                <DirectionsRenderer 
                  directions={directionsResponse} 
                  options={{
                    suppressMarkers: false, 
                    polylineOptions: {
                      strokeColor: '#3b82f6',
                      strokeWeight: 5,
                      strokeOpacity: 0.8
                    }
                  }}
                />
              )}

              {/* Draw Buses */}
              {buses.map(bus => {
                const lat = busLocations[bus._id]?.lat || bus.currentLocation?.lat;
                const lng = busLocations[bus._id]?.lng || bus.currentLocation?.lng;
                
                if (!lat || !lng) return null;

                return (
                  <Marker
                    key={bus._id}
                    position={{ lat, lng }}
                    icon={{
                      url: '/bus.svg',
                      scaledSize: new window.google.maps.Size(40, 40)
                    }}
                    onClick={() => setSelectedBus(bus)}
                  />
                );
              })}
            </GoogleMap>
          )}
        </div>
      </div>
    </div>
  );
};

export default StudentDashboard;